---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test-namespace
  name: fake-dashboard
  labels:
    fake-dashboard: "yea"
data:
  test-first-dashboard: |-
     This is the first dashboard in the test-namespace
  test-second-dashboard: |-
     This is the second dashboard in the test-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-dashboard-2
  labels:
    fake-dashboard: "yea"
data:
  default-dashboard: |-
     This is a dashboard in the default namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-dashboard-folder-annotation
  annotations:
    annotation-path: "/tmp/bar/foo"
  labels:
    fake-dashboard: "yea"
data:
  default-annotation: |-
     This dashboard should be in /tmp/bar/foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-dashboard-folder-annotation-relative
  annotations:
    annotation-path: "something"
  labels:
    fake-dashboard: "yea"
data:
  default-annotation-relative: |-
     This dashboard should be in /tmp/something
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-dashboard-multine
  labels:
    fake-dashboard: "yea"
data:
  default-dashboard-multiline: |-
     This is line 1
     This is line 2
     This is line 3
     This is line 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-datasource-1
  labels:
    fake-datasource: "yea"
data:
  default-datasource-1: |-
     This is a datasource in the default namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test-namespace
  name: fake-datasource-2
  labels:
    fake-datasource: "yea"
data:
  default-datasource-2: |-
     This is a datasource in the test-namespace
