---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test-namespace
  name: sample-configmap
  labels:
    findme: "yea"
data:
  test-first-file: |-
     Hello World in test namespace. This is the first file.
  test-second-file: |-
     Hello World in test namespace. This is the second file.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap-different-folder
  annotations:
    annotation-path: "/tmp/bar/foo"
  labels:
    findme: "yea"
data:
  default-annotation: |-
     This file should be in /tmp/bar/foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  labels:
    findme: "yea"
data:
  default-file: |-
     Hello World in default namespace.
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: sample-configmap-from-url
#   namespace: prometheus-operator
#   labels:
#     findme: "yea"
# data:
#   # fetch https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json with the grafana sidecar
#   # .url will be stripped and the file will be called nginx-ingress.json
#   nginx-ingress.json.url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
