---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      serviceAccountName: sample-acc
      containers:
        - name: bash
          image: bash:4.4.19
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/
          command: ["watch"]
          args: ["for file in /tmp/*; do tail -v -n +1 $file; echo; done"]
        - name: sidecar
          imagePullPolicy: Always
          # image: kiwigrid/k8s-sidecar:latest
          image: omegavveapon/kopf-k8s-sidecar:fix-init-container
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/
          env:
            - name: UNIQUE_FILENAMES
              value: "true"
            # - name: DEBUG
            #   value: "true"
            # - name: VERBOSE
            #   value: "true"
            # - name: NAMESPACE
            #   value: test-namespace,default
            # - name: METHOD
            #   value: "LIST"
            - name: LABEL
              value: "findme"
            - name: LABEL_VALUE
              value: "yea"
            - name: FOLDER
              value: /tmp/
            - name: FOLDER_ANNOTATION
              value: "annotation-path"
            - name: RESOURCE
              value: both
      volumes:
        - name: shared-volume
          emptyDir: {}
